import type {
  CodexSession,
  CodexStatus,
  CodexCatalogModel,
  Dashboard,
  Gateway,
  IMAccount,
  Lifecycle,
  RequestLog,
  Settings,
  Sub2ApiAdmin,
  Sub2ApiPool,
} from "./types";

const now = Date.now();

export const fixtureCodexModelCatalog: CodexCatalogModel[] = [
  { id: "gpt-5.4", displayName: "GPT-5.4" },
  { id: "gpt-5.4-mini", displayName: "GPT-5.4 mini" },
  { id: "gpt-5.3-codex", displayName: "GPT-5.3 Codex" },
  { id: "claude-opus-4-1", displayName: "Claude Opus 4.1" },
];

export const fixtureDashboard: Dashboard = {
  service: {
    service: "mochiport",
    apiMajor: 1,
    ready: true,
    instanceId: "fixture-mochiport-daemon",
    pid: 14812,
    startedAtMs: now - 1000 * 60 * 74,
  },
  bridgeRunning: true,
  remoteControlConnected: true,
  remoteControlHealthy: true,
  executionClients: {
    codexApp: { configured: true, connected: true },
    vscode: { configured: true, connected: false },
    cli: { configured: true, connected: false },
  },
  messageChannels: {
    telegram: { accountCount: 1, connectedAccountCount: 1 },
    feishu: { accountCount: 1, connectedAccountCount: 1 },
    wechat: { accountCount: 0, connectedAccountCount: 0 },
    wecom: { accountCount: 0, connectedAccountCount: 0 },
  },
  aiGatewayEnabled: true,
  aiGatewayProviderCount: 2,
  requestLoggingEnabled: true,
};

export const fixtureLifecycle: Lifecycle = {
  service: fixtureDashboard.service,
  executable: "C:\\Program Files\\MochiPort\\mochiport-daemon.exe",
  executableSha256: "fixture",
  configPath: "C:\\Users\\Mia\\AppData\\Local\\MochiPort\\config.toml",
  bind: "127.0.0.1:3847",
  runtime: { state: "running", productVersion: "0.5.2", buildNumber: 445, apiMajor: 1 },
  protectedWorkItems: {
    aiGatewayRequests: 0,
    codexTurns: 1,
    imStreams: 0,
    pendingApprovals: 0,
    remoteControlRequests: 1,
    total: 2,
  },
  management: {
    state: "owned",
    mode: "lease",
    canControl: true,
    installationId: "fixture-windows-installation",
    leaseGeneration: 3,
    managementTokenGeneration: 2,
  },
};

export const fixtureCodexStatus: CodexStatus = {
  codexHome: "C:\\Users\\Mia\\.codex",
  configured: true,
  configOk: true,
  authOk: true,
  providerOk: true,
  guiConfigured: true,
  remoteControlSupported: true,
  remoteControlConfigured: true,
  providers: [
    { name: "MochiPort", baseUrl: "http://127.0.0.1:3847/ai-gateway/v1", secretSet: true, supportsWebsockets: true },
  ],
  imageGenerationEnabled: true,
  connectionMode: "remoteControl",
  providerMode: "mochiport",
  providerModeMessage: "Codex 通过 MochiPort AI 网关连接模型服务",
  activeProvider: "MochiPort",
};

export const fixtureGateway: Gateway = {
  enabled: true,
  filterImageGenerationTool: false,
  requestLoggingEnabled: true,
  requestLogDetailsEnabled: false,
  codexVisibleModels: ["gpt-5.4", "claude-opus-4-1"],
  providers: [
    {
      name: "OpenAI",
      enabled: true,
      providerType: "open_ai_responses",
      compatibility: null,
      baseUrl: "https://api.openai.com/v1",
      modelsUrl: null,
      models: ["gpt-5.4", "gpt-5.4-mini"],
      modelAliases: {},
      promptCacheRetention: null,
      weight: 100,
      timeoutSecs: 120,
      secretSet: true,
    },
    {
      name: "Anthropic",
      enabled: true,
      providerType: "anthropic_messages",
      compatibility: null,
      baseUrl: "https://api.anthropic.com/v1",
      modelsUrl: null,
      models: ["claude-opus-4-1", "claude-sonnet-4-1"],
      modelAliases: {},
      promptCacheRetention: "1h",
      weight: 80,
      timeoutSecs: 120,
      secretSet: true,
    },
  ],
};

export const fixtureAccounts: IMAccount[] = [
  {
    platform: "telegram",
    accountId: "7251034182",
    displayName: "MochiPort Bot",
    avatarData: null,
    enabled: true,
    configured: true,
    secretSet: true,
    connecting: false,
    polling: true,
    connected: true,
    lastError: null,
    lastEventAtMs: now - 32_000,
    lastInboundAtMs: now - 120_000,
  },
  {
    platform: "feishu",
    accountId: "cli_a84c83f1",
    displayName: "MochiPort 工作助手",
    avatarData: null,
    enabled: true,
    configured: true,
    secretSet: true,
    connecting: false,
    polling: false,
    connected: true,
    lastError: null,
    lastEventAtMs: now - 14_000,
    lastInboundAtMs: now - 65_000,
  },
];

export const fixtureSessions: CodexSession[] = [
  {
    id: "019d1e6c-8f22-7c01-a8aa-b20f01aaea5e",
    name: "Windows 客户端界面复刻",
    preview: "复刻 Mac 端各个页面并接入 Tauri 管理 API",
    modelProvider: "MochiPort",
    updatedAt: Math.floor((now - 85_000) / 1000),
    cwd: "C:\\Code\\mochiport",
  },
  {
    id: "019d1e1a-20f1-72ca-9d60-7f31576f4f5c",
    name: "优化消息渠道接入",
    preview: "检查 Telegram 和飞书账号的连接状态",
    modelProvider: "openai",
    updatedAt: Math.floor((now - 1000 * 60 * 47) / 1000),
    cwd: "C:\\Code\\mochiport",
  },
  {
    id: "019d1d09-7a71-7828-9431-6ef49982a51c",
    name: null,
    preview: "整理发布检查清单",
    modelProvider: "MochiPort",
    updatedAt: Math.floor((now - 1000 * 60 * 60 * 3) / 1000),
    cwd: "D:\\Projects\\release-notes",
  },
];

export const fixtureLogs: RequestLog[] = [
  {
    id: 321,
    requestId: "req_8c5d26a1",
    modelId: "gpt-5.4",
    stream: true,
    channel: "primary",
    providerType: "open_ai_responses",
    status: "completed",
    inputTokens: 18420,
    outputTokens: 2461,
    totalTokens: 20881,
    readCacheTokens: 12_640,
    readCacheHitRate: 0.6862,
    writeCacheTokens: 3_072,
    writeCache5mTokens: 2_048,
    writeCache1hTokens: 1_024,
    costUsd: 0.0874,
    latencyMs: 12_482,
    ttftMs: 718,
    createdAtMs: now - 46_000,
    createdAt: new Date(now - 46_000).toISOString(),
    upstreamRequestBodyBytes: 18_432,
  },
  {
    id: 320,
    requestId: "req_2e4af730",
    modelId: "claude-opus-4-1",
    stream: true,
    channel: "telegram",
    providerType: "anthropic_messages",
    status: "completed",
    inputTokens: 7260,
    outputTokens: 1214,
    totalTokens: 8474,
    readCacheTokens: 5_880,
    readCacheHitRate: 0.81,
    writeCacheTokens: 640,
    writeCache5mTokens: 640,
    writeCache1hTokens: 0,
    costUsd: 0.0542,
    latencyMs: 8_120,
    ttftMs: 906,
    createdAtMs: now - 1000 * 60 * 11,
    createdAt: new Date(now - 1000 * 60 * 11).toISOString(),
    upstreamRequestBodyBytes: 9_216,
  },
  {
    id: 319,
    requestId: "req_81e9010f",
    modelId: "gpt-5.4-mini",
    stream: false,
    channel: "feishu",
    providerType: "open_ai_responses",
    status: "failed",
    inputTokens: 901,
    outputTokens: 0,
    totalTokens: 901,
    readCacheTokens: 0,
    readCacheHitRate: 0,
    writeCacheTokens: 0,
    latencyMs: 2_043,
    createdAtMs: now - 1000 * 60 * 28,
    createdAt: new Date(now - 1000 * 60 * 28).toISOString(),
    errorMessage: "上游服务暂时不可用",
    upstreamRequestBodyBytes: 1_024,
  },
];

export const fixtureSettings: Settings = {
  language: "zh-CN",
  theme: "system",
  localConnectionMode: "standard",
  bind: "127.0.0.1:3847",
  outboundProxy: { mode: "system", url: "<none>", credentialSet: false },
};

export const fixtureSub2ApiAdmin: Sub2ApiAdmin = {
  configured: true,
  baseUrl: "https://sub2api.example.com",
  secretSet: true,
};

export const fixtureSub2ApiPool: Sub2ApiPool = {
  source: "sub2api",
  fetchedAtMs: now - 24_000,
  warnings: null,
  accounts: [
    {
      id: 12,
      name: "OpenAI 主账号",
      siteUrl: "https://api.openai.com",
      platform: "openai",
      accountType: "api",
      status: "active",
      schedulable: true,
      localRateMultiplier: 1,
      upstreamBilling: { state: "available", effectiveRateMultiplier: 1, stale: false },
      upstreamBalance: { state: "available", remaining: 42.86, unlimited: false, unit: "USD" },
    },
    {
      id: 18,
      name: "Claude 工作区",
      siteUrl: "https://api.anthropic.com",
      platform: "anthropic",
      accountType: "workspace",
      status: "active",
      schedulable: true,
      localRateMultiplier: 0.8,
      upstreamBilling: { state: "available", effectiveRateMultiplier: 0.8, stale: false },
      upstreamBalance: { state: "available", remaining: null, unlimited: true, unit: "USD" },
    },
  ],
};
