#!/usr/bin/env python3
"""Generate the macOS and Windows client contracts from the daemon's JSON Schema.

The daemon owns the management API contract; the clients consume it. Instead of
hand-maintaining a Swift `Decodable` implementation and a set of TypeScript
types beside every response, both clients are generated from the schema the
daemon exports (`contracts/manage-contracts.schema.json`).

Decoding stays tolerant the way the hand-written clients were: a property that
is absent from `required` but carries a `default` decodes to that default, and
any other non-required property decodes to an optional value.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

SWIFT_INTEGERS = {
    "uint8": "UInt8",
    "uint16": "UInt16",
    "uint32": "UInt32",
    "uint64": "UInt64",
    "int8": "Int8",
    "int16": "Int16",
    "int32": "Int32",
    "int64": "Int64",
}

HEADER = "// Generated by scripts/generate-client-contracts.py -- do not edit by hand."
SCHEMA_DRAFT = "https://json-schema.org/draft/2020-12/schema"

# Emitted only when a generated contract references it: the daemon returns untyped
# payloads (error bodies) in a few places, and Swift's Codable has no `Any`.
JSON_VALUE_SWIFT = """/// Any JSON value, used where the daemon returns an untyped payload.
public enum JsonValue: Codable, Sendable, Equatable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case object([String: JsonValue])
    case array([JsonValue])
    case null

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if container.decodeNil() {
            self = .null
        } else if let value = try? container.decode(Bool.self) {
            self = .bool(value)
        } else if let value = try? container.decode(Double.self) {
            self = .number(value)
        } else if let value = try? container.decode(String.self) {
            self = .string(value)
        } else if let value = try? container.decode([String: JsonValue].self) {
            self = .object(value)
        } else if let value = try? container.decode([JsonValue].self) {
            self = .array(value)
        } else {
            throw DecodingError.dataCorruptedError(
                in: container,
                debugDescription: "unsupported JSON value"
            )
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case let .string(value): try container.encode(value)
        case let .number(value): try container.encode(value)
        case let .bool(value): try container.encode(value)
        case let .object(value): try container.encode(value)
        case let .array(value): try container.encode(value)
        case .null: try container.encodeNil()
        }
    }
}"""


class ContractError(RuntimeError):
    pass


def normalize(definition: object) -> dict[str, object]:
    """JSON Schema allows a boolean where a schema object is expected.

    schemars renders `serde_json::Value` as `true` (any value is valid), so every
    entry point normalises booleans instead of dropping the property silently.
    """
    if isinstance(definition, bool):
        return {} if definition else {"not": {}}
    if isinstance(definition, dict):
        return definition
    return {}


def type_names(definition: dict[str, object]) -> list[str]:
    raw = definition.get("type")
    if raw is None:
        return []
    if isinstance(raw, str):
        return [raw]
    return [str(entry) for entry in raw]


def collapse_nullable_anyof(definition: dict[str, object]) -> dict[str, object]:
    """Rewrites `anyOf: [X, null]` into the `["X", "null"]` form.

    schemars renders `Option<T>` for a referenced type as `anyOf: [$ref, null]`
    rather than a `type` array. Both mean "nullable T", but only the collapsed
    form resolves to a real Swift/TypeScript type instead of an opaque value.
    """
    for key in ("anyOf", "oneOf"):
        options = definition.get(key)
        if not isinstance(options, list) or len(options) != 2:
            continue
        null_like = [
            option
            for option in options
            if isinstance(option, dict) and option.get("type") == "null"
        ]
        others = [option for option in options if option not in null_like]
        if len(null_like) != 1 or len(others) != 1 or not isinstance(others[0], dict):
            continue
        inner = others[0]
        # Keep the description on the collapsed definition, not on the branch.
        collapsed = {k: v for k, v in definition.items() if k != key}
        if "description" not in collapsed and isinstance(inner.get("description"), str):
            collapsed["description"] = inner["description"]
        for name, value in inner.items():
            if name != "description":
                collapsed[name] = value
        return collapsed
    return definition


def ref_name(definition: dict[str, object]) -> str | None:
    reference = definition.get("$ref")
    if isinstance(reference, str) and reference.startswith("#/$defs/"):
        return reference[len("#/$defs/") :]
    return None


def is_numeric(value: object) -> bool:
    return isinstance(value, (int, float)) and not isinstance(value, bool)


def is_simple_default(value: object) -> bool:
    """Whether a JSON Schema `default` can be written as a Swift/TS literal.

    `#[serde(default)]` on a nested struct expands into that struct's whole
    default object, which has no literal form. Such fields decode as optional
    values instead of being given a synthesised default.
    """
    if isinstance(value, (bool, str)):
        return True
    if is_numeric(value):
        return True
    return isinstance(value, list) and not value


def base_of(definition: dict[str, object], defs: dict[str, object]) -> str:
    return swift_type(definition, defs)[0]


def swift_default(
    definition: dict[str, object], swift_type: str, defs: dict[str, object]
) -> str | None:
    if "default" not in definition:
        return None
    value = definition["default"]
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        target = defs.get(swift_type)
        # A string default for an enum-typed field has to go through its raw value.
        if isinstance(target, dict) and isinstance(target.get("enum"), list):
            return f"{swift_type}(rawValue: {json.dumps(value, ensure_ascii=False)})!"
        return json.dumps(value, ensure_ascii=False)
    if is_numeric(value):
        return repr(value)
    if isinstance(value, list) and not value:
        return "[]"
    return None


def ts_default(definition: dict[str, object]) -> str | None:
    if "default" not in definition:
        return None
    value = definition["default"]
    if isinstance(value, list) and not value:
        return "[]"
    return None


def swift_literal(value: object) -> str | None:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if is_numeric(value):
        return repr(value)
    return None


def swift_type(definition: dict[str, object], defs: dict[str, object]) -> tuple[str, bool]:
    """Return (swift type without optional marker, is nullable)."""
    definition = normalize(definition)
    nested = ref_name(definition)
    if nested is not None:
        return nested, False
    kinds = type_names(definition)
    nullable = "null" in kinds
    effective = [kind for kind in kinds if kind != "null"]
    if not effective:
        return "JsonValue", True
    kind = effective[0]
    if kind == "string":
        return "String", nullable
    if kind == "boolean":
        return "Bool", nullable
    if kind == "integer":
        return SWIFT_INTEGERS.get(str(definition.get("format", "")), "Int"), nullable
    if kind == "number":
        return "Double", nullable
    if kind == "array":
        inner, _ = swift_type(definition.get("items", {}), defs)
        return f"[{inner}]", nullable
    if kind == "object":
        additional = definition.get("additionalProperties")
        if isinstance(additional, dict):
            inner, _ = swift_type(additional, defs)
            return f"[String: {inner}]", nullable
        if isinstance(definition.get("properties"), dict):
            return "JsonValue", nullable
        return "[String: JsonValue]", nullable
    raise ContractError(f"unsupported Swift type: {definition!r}")


def ts_type(definition: dict[str, object], defs: dict[str, object]) -> str:
    definition = normalize(definition)
    nested = ref_name(definition)
    if nested is not None:
        return nested
    kinds = type_names(definition)
    nullable = "null" in kinds
    effective = [kind for kind in kinds if kind != "null"]
    if not effective:
        return "unknown"
    kind = effective[0]
    if kind == "string":
        rendered = "string"
    elif kind == "boolean":
        rendered = "boolean"
    elif kind in ("integer", "number"):
        rendered = "number"
    elif kind == "array":
        rendered = f"{ts_type(definition.get('items', {}), defs)}[]"
    elif kind == "object":
        additional = definition.get("additionalProperties")
        if isinstance(additional, dict):
            rendered = f"Record<string, {ts_type(additional, defs)}>"
        else:
            rendered = "Record<string, unknown>"
    else:
        raise ContractError(f"unsupported TypeScript type: {definition!r}")
    return f"{rendered} | null" if nullable else rendered


def sorted_properties(definition: dict[str, object]) -> list[tuple[str, dict[str, object]]]:
    properties = definition.get("properties")
    if not isinstance(properties, dict):
        return []
    return sorted(
        (
            (str(name), collapse_nullable_anyof(normalize(entry)))
            for name, entry in properties.items()
        ),
        key=lambda item: item[0].casefold(),
    )


def emit_swift_enum(name: str, definition: dict[str, object]) -> str:
    values = definition.get("enum")
    if not isinstance(values, list):
        raise ContractError(f"{name}: enum without values")
    lines = [f"public enum {name}: String, Codable, Sendable, Equatable, CaseIterable {{"]
    for value in values:
        if not isinstance(value, str):
            raise ContractError(f"{name}: only string enums are supported")
        member = value.replace("-", "_")
        lines.append(f'    case {member} = {json.dumps(value, ensure_ascii=False)}')
    lines.append("}")
    return "\n".join(lines)


def emit_swift_struct(name: str, definition: dict[str, object], defs: dict[str, object]) -> str:
    required = {str(entry) for entry in definition.get("required", []) if isinstance(entry, str)}
    properties = sorted_properties(definition)
    lines = [f"public struct {name}: Codable, Sendable, Equatable {{"]
    decoders: list[str] = []
    for field, spec in properties:
        base, nullable = swift_type(spec, defs)
        has_default = "default" in spec
        if field in required:
            lines.append(f"    public let {field}: {base}")
            decoders.append(f"        {field} = try container.decode({base}.self, forKey: .{field})")
            continue
        if has_default and is_simple_default(spec["default"]):
            default = swift_default(spec, base, defs)
            if default is None:
                raise ContractError(f"{name}.{field}: unsupported default {spec['default']!r}")
            lines.append(f"    public let {field}: {base}")
            decoders.append(
                f"        {field} = try container.decodeIfPresent({base}.self, forKey: .{field}) ?? {default}"
            )
            continue
        optional = f"{base}?" if not nullable else f"{base}?"
        lines.append(f"    public let {field}: {optional}")
        decoders.append(
            f"        {field} = try container.decodeIfPresent({base}.self, forKey: .{field})"
        )
    lines.append("")
    lines.append("    public init(from decoder: Decoder) throws {")
    lines.append("        let container = try decoder.container(keyedBy: CodingKeys.self)")
    lines.extend(decoders)
    lines.append("    }")
    lines.append("")
    lines.append("    private enum CodingKeys: String, CodingKey {")
    for field, _ in properties:
        lines.append(f"        case {field}")
    lines.append("    }")
    lines.append("")

    # A memberwise initialiser keeps the generated type a drop-in replacement for
    # the hand-written structs it replaces, whose call sites construct them directly.
    parameters = []
    assignments = []
    for field, spec in properties:
        if field not in required:
            continue
        base, _ = swift_type(spec, defs)
        parameters.append(f"{field}: {base}")
        assignments.append(f"        self.{field} = {field}")
    for field, spec in properties:
        if field in required:
            continue
        if "default" in spec and is_simple_default(spec["default"]):
            assignments.append(
                f"        self.{field} = {swift_default(spec, base_of(spec, defs), defs)}"
            )
        else:
            assignments.append(f"        self.{field} = nil")
    lines.append(f"    public init({', '.join(parameters)}) {{")
    lines.extend(assignments)
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines)


def emit_ts(definition: dict[str, object], name: str, defs: dict[str, object], indent: str = "") -> str:
    required = {str(entry) for entry in definition.get("required", []) if isinstance(entry, str)}
    lines = [f"{indent}export interface {name} {{"]
    for field, spec in sorted_properties(definition):
        rendered = ts_type(spec, defs)
        has_literal_default = "default" in spec and is_simple_default(spec["default"])
        optional = "" if field in required or has_literal_default else "?"
        lines.append(f"{indent}  {field}{optional}: {rendered};")
    lines.append(f"{indent}}}")
    return "\n".join(lines)


def emit_ts_enum(name: str, definition: dict[str, object]) -> str:
    values = definition.get("enum")
    if not isinstance(values, list):
        raise ContractError(f"{name}: enum without values")
    rendered = " | ".join(json.dumps(str(value), ensure_ascii=False) for value in values)
    return f"export type {name} = {rendered};"


def emit_swift(name: str, definition: dict[str, object], defs: dict[str, object]) -> str:
    if isinstance(definition.get("enum"), list):
        return emit_swift_enum(name, definition)
    if "object" in type_names(definition) or isinstance(definition.get("properties"), dict):
        return emit_swift_struct(name, definition, defs)
    kind = swift_type(definition, defs)[0]
    return f"public typealias {name} = {kind}"


def normalize_enum(definition: dict[str, object]) -> dict[str, object]:
    """Collapse a `oneOf` of string constants into a plain string enum.

    schemars emits that shape when every enum variant carries its own doc
    comment, which is common in this codebase. Both forms describe the same
    contract, but only the collapsed one maps onto a Swift enum instead of an
    opaque JSON value.
    """
    one_of = definition.get("oneOf")
    if not isinstance(one_of, list) or not one_of:
        return definition
    values: list[str] = []
    for entry in one_of:
        if not isinstance(entry, dict):
            return definition
        if entry.get("type") != "string" or not isinstance(entry.get("const"), str):
            return definition
        values.append(entry["const"])
    collapsed = {key: value for key, value in definition.items() if key != "oneOf"}
    collapsed["type"] = "string"
    collapsed["enum"] = values
    return collapsed


def normalize_definition(definition: dict[str, object]) -> dict[str, object]:
    """Applies every normalisation in the order they can depend on each other."""
    return collapse_nullable_anyof(normalize_enum(definition))


def gather(schema: dict[str, object]) -> dict[str, dict[str, object]]:
    defs = schema.get("$defs")
    if not isinstance(defs, dict) or not defs:
        raise ContractError("schema has no $defs; export a catalogue type instead")
    collected: dict[str, dict[str, object]] = {}
    for name, definition in defs.items():
        if not isinstance(definition, dict):
            raise ContractError(f"{name}: definition must be an object")
        collected[str(name)] = normalize_definition(definition)
    return collected


TS_RUNTIME_HELPERS = """export type Validator<T> = (value: unknown) => value is T;

type JsonObject = Record<string, unknown>;

const isObject = (value: unknown): value is JsonObject =>
  typeof value === "object" && value !== null && !Array.isArray(value);
const isString = (value: unknown): value is string => typeof value === "string";
const isNumber = (value: unknown): value is number =>
  typeof value === "number" && Number.isFinite(value);
const isInteger = (value: unknown): value is number => isNumber(value) && Number.isInteger(value);
const isBoolean = (value: unknown): value is boolean => typeof value === "boolean";
"""


def ts_check(expression: str, definition: object, defs: dict[str, object]) -> str:
    """Builds the runtime predicate for one schema fragment.

    The clients validate management responses at runtime as well as at compile
    time, so the generator emits guards alongside the types.
    """
    spec = normalize(definition)
    nested = ref_name(spec)
    if nested is not None:
        return f"is{nested}({expression})"

    kinds = type_names(spec)
    nullable = "null" in kinds
    effective = [kind for kind in kinds if kind != "null"]
    if not effective:
        # Any JSON value is acceptable; only its presence can be checked.
        return "true"

    kind = effective[0]
    if kind == "string":
        check = f"isString({expression})"
    elif kind == "boolean":
        check = f"isBoolean({expression})"
    elif kind == "integer":
        check = f"isInteger({expression})"
    elif kind == "number":
        check = f"isNumber({expression})"
    elif kind == "array":
        inner = ts_check("entry", spec.get("items", {}), defs)
        check = f"Array.isArray({expression}) && {expression}.every((entry) => {inner})"
    elif kind == "object":
        additional = spec.get("additionalProperties")
        if isinstance(additional, dict):
            inner = ts_check("entry", additional, defs)
            check = (
                f"isObject({expression})"
                f" && Object.values({expression}).every((entry) => {inner})"
            )
        else:
            check = f"isObject({expression})"
    else:
        check = "true"

    return f"({expression} === null || {check})" if nullable else f"({check})"


def emit_ts_validator(name: str, definition: dict[str, object], defs: dict[str, object]) -> str:
    values = definition.get("enum")
    if isinstance(values, list):
        checks = " || ".join(
            f"value === {json.dumps(str(value), ensure_ascii=False)}" for value in values
        )
        return f"export const is{name}: Validator<{name}> = (value): value is {name} =>\n  {checks};"

    if "object" in type_names(definition) or isinstance(definition.get("properties"), dict):
        required = {str(entry) for entry in definition.get("required", []) if isinstance(entry, str)}
        lines = [
            f"export const is{name}: Validator<{name}> = (value): value is {name} =>",
            "  isObject(value)",
        ]
        for field, spec in sorted_properties(definition):
            check = ts_check(f"value.{field}", spec, defs)
            if field in required:
                lines.append(f"  && {check}")
            else:
                # Optional in the schema: absent is valid, present must match.
                lines.append(f"  && (value.{field} === undefined || {check})")
        return "\n".join(lines) + ";"
    return ""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("schema", type=Path, help="JSON Schema exported by the daemon")
    parser.add_argument("--swift", type=Path, required=True, help="Swift output path")
    parser.add_argument("--typescript", type=Path, required=True, help="TypeScript output path")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when the checked-in output is stale",
    )
    args = parser.parse_args()

    schema = json.loads(args.schema.read_text(encoding="utf-8"))
    defs = gather(schema)
    ordered = sorted(defs, key=str.casefold)

    swift_sections: list[str] = []
    ts_sections = [HEADER, "", TS_RUNTIME_HELPERS]
    for name in ordered:
        definition = defs[name]
        swift_sections.append(emit_swift(name, definition, defs))
        swift_sections.append("")
        if isinstance(definition.get("enum"), list):
            ts_sections.append(emit_ts_enum(name, definition))
        elif "object" in type_names(definition) or isinstance(definition.get("properties"), dict):
            ts_sections.append(emit_ts(definition, name, defs))
        else:
            ts_sections.append(f"export type {name} = {ts_type(definition, defs)};")
        validator = emit_ts_validator(name, definition, defs)
        if validator:
            ts_sections.append("")
            ts_sections.append(validator)
        ts_sections.append("")

    swift_body = "\n".join(swift_sections).rstrip() + "\n"
    swift_header = f"{HEADER}\n\nimport Foundation\n"
    if "JsonValue" in swift_body:
        swift_header += f"\n{JSON_VALUE_SWIFT}\n"
    swift_content = f"{swift_header}\n{swift_body}"

    outputs = [
        (args.swift, swift_content),
        (args.typescript, "\n".join(ts_sections).rstrip() + "\n"),
    ]
    stale = [path for path, content in outputs if not path.exists() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            for path in stale:
                print(f"stale generated contract: {path}", flush=True)
            return 1
        print("generated contracts are up to date")
        return 0
    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
