//
// TokenCompanionAnimator.swift
// Auto-generated by svg-character-animator skill (scripts/export-swift.js)
// Generated: 2026-08-21T03:49:14.244Z
// Source: TokenCompanion.states.js
//
// Usage:
//   1. Drop this file into your Xcode project.
//   2. Embed in any view: `TokenCompanionAnimator()` (it manages its own state).
//      For external control, use the public `state` binding initializer.
//
// Requirements: iOS 15+ (TimelineView), iOS 17+ recommended for smoother
// keyframeAnimator transitions. No external dependencies.
//
// What's exported:
//   - 2 states, 12 shared paths
//   - Per-state idle animations (sway, breathe-y, compound, etc.)
//   - Per-state particle systems (where configured)
//   - Morph easing: easeInOutQuad @ 1200ms
//   - The preview's background color is preview-only: this view renders on a
//     transparent canvas — put your own background behind it in the host app.
//
// Features handled by this generator:
//   - TRANSFORM-strategy paths: per-control-point lerp, preserves bezier curves exactly.
//   - MORPH-strategy paths: polygon-sampled to 80 vertices per state, lerped vertex-by-vertex.
//   - Multi-subpath stroke paths (hands): rigid-body translate+rotate transition
//     around the wrist anchor. Stroke caps stay welded to their fingers, no stretching.
//   - Per-path transform attributes (e.g. head tilt): animated via MorphRotation modifier.
//   - Orphan SVG decorations: rendered as native SwiftUI Paths with proper fills
//     (solid color or RadialGradient/LinearGradient matched to source defs).
//     Gradient fills use .mask() so UnitPoint normalizes to the canvas, matching
//     SVG's userSpaceOnUse semantics.
//   - Orphan crossfade: each state's orphan layer fades in/out via a separate
//     displayedOrphanState driven inside withAnimation at transition start.
//   - Particle templates: each state's orphanSVG top-level groups are rendered to
//     UIImages at build time and fed as multiple CAEmitterCells, so the emitter
//     spawns real flower variants — not a placeholder circle.
//   - Particle emission gating: emission stops immediately at the start of any
//     transition leaving the particle state; alive cells finish their lifetime.
//
// Known limitations:
//   - Elliptical/rotated gradients are approximated as circular (max axis radius).
//     Exact reproduction would need a Metal shader.
//   - Rapid interrupts during a morph re-snap to displayedState's geometry rather
//     than continuing from the live mid-morph shape (SwiftUI can't easily read its
//     own current Shape output). The JS preview reads live d's for smoother interrupts.
//   - Per-element idle (selectorAll / selector parts) is applied as a full
//     transform (offset + rotation + scale + blink squish + opacity) via
//     idleForElement + TokenCompanionElementIdleMod. Looping orphan bursts (orphanPopLoop)
//     start from their natural t=0 phase rather than the JS "skipAppear" first
//     cycle — steady-state is identical, only the first ~1s differs.
//
// Generated for any well-formed states file. The script handles automatically:
//   * Any number of states with any state-machine topology (N×N transitions)
//   * Per-id TRANSFORM vs MORPH strategy (fingerprinted at export time)
//   * Multi-subpath stroke paths via rigid-body translate+rotate
//   * Per-path rotate(deg cx cy) attribute animated via MorphRotation
//   * Orphan back/front layering via the source SVG's _layer hint
//   * Gradient fills (radial + linear) from <defs>, with userSpaceOnUse semantics
//   * Particle templates from BOTH orphanSVG groups AND structured _orphan paths
//   * Per-state idle: sway, breathe, breathe-y, bob, shake, waggle-sequence,
//     rotate-around-point (with optional gating), and any compound combination
//   * Crossfade orphan transitions driven by displayedOrphanState
//   * Layer-aware particle compositing (behind shared paths when configured)
//

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - State enum

public enum TokenCompanionState: String, CaseIterable, Hashable {
    case idle
    case happy
}

// MARK: - Path segment representation

enum TokenCompanionMorphPathSegment {
    case move(CGPoint)
    case line(CGPoint)
    case curve(to: CGPoint, c1: CGPoint, c2: CGPoint)
    case quad(to: CGPoint, c: CGPoint)
    case close
}

extension Path {
    init(tokenCompanion segments: [TokenCompanionMorphPathSegment]) {
        self.init()
        for seg in segments {
            switch seg {
            case .move(let p): self.move(to: p)
            case .line(let p): self.addLine(to: p)
            case .curve(let to, let c1, let c2): self.addCurve(to: to, control1: c1, control2: c2)
            case .quad(let to, let c): self.addQuadCurve(to: to, control: c)
            case .close: self.closeSubpath()
            }
        }
    }
}

// Lerp helpers — TRANSFORM strategy: same segment count + commands across
// states, lerp every control point. Falls back to snap on mismatch.
private func lerpP(_ a: CGPoint, _ b: CGPoint, _ t: Double) -> CGPoint {
    CGPoint(x: a.x + (b.x - a.x) * t, y: a.y + (b.y - a.y) * t)
}
// The control points of one segment, in a fixed slot order. Used by the
// rotation-aware lerp to walk corresponding points across two same-structure
// segment lists. Order is irrelevant to the centroid/theta sums and only has
// to be consistent between the two lists (it is — same command ⇒ same slots).
private func segPoints(_ s: TokenCompanionMorphPathSegment) -> [CGPoint] {
    switch s {
    case let .move(p): return [p]
    case let .line(p): return [p]
    case let .curve(to, c1, c2): return [to, c1, c2]
    case let .quad(to, c): return [to, c]
    case .close: return []
    }
}

// Rotation-aware control-point interpolation (2D Kabsch). Naively lerping
// each control point makes a shape that ROTATES between poses collapse toward
// its centroid at the midpoint — every vertex cuts across the chord instead
// of following the arc (this shrank a character's wings as they swung up).
//
// Fix: estimate the rigid motion between the two point sets — centroid shift
// plus the least-squares optimal rotation theta (atan2 of summed cross/dot of
// the centered points) — then lerp only the *residual* in a shared de-rotated
// frame and rotate it forward by theta*t. A pure rotation animates rigidly;
// a pure deformation (theta ~ 0) degrades to plain linear lerp exactly, so
// non-rotating parts (body, head) are unaffected. Matches the JS engine's
// interpolateStructuredPaths.
private func lerpSegments(_ a: [TokenCompanionMorphPathSegment], _ b: [TokenCompanionMorphPathSegment], _ t: Double) -> [TokenCompanionMorphPathSegment] {
    guard a.count == b.count else { return t < 0.5 ? a : b }
    // Pass 1: centroids of every control point in each pose.
    var n = 0.0, sumFx = 0.0, sumFy = 0.0, sumTx = 0.0, sumTy = 0.0
    for i in 0..<a.count {
        let pf = segPoints(a[i]), pt = segPoints(b[i])
        guard pf.count == pt.count else { return t < 0.5 ? a : b }
        for j in 0..<pf.count {
            sumFx += pf[j].x; sumFy += pf[j].y
            sumTx += pt[j].x; sumTy += pt[j].y
            n += 1
        }
    }
    guard n > 0 else { return a }
    let cFx = sumFx / n, cFy = sumFy / n, cTx = sumTx / n, cTy = sumTy / n
    // Pass 2: optimal rotation theta between the centered point clouds.
    var cross = 0.0, dot = 0.0
    for i in 0..<a.count {
        let pf = segPoints(a[i]), pt = segPoints(b[i])
        for j in 0..<pf.count {
            let ax = pf[j].x - cFx, ay = pf[j].y - cFy
            let bx = pt[j].x - cTx, by = pt[j].y - cTy
            dot += ax * bx + ay * by
            cross += ax * by - ay * bx
        }
    }
    let theta = atan2(cross, dot)
    let cxT = cFx + (cTx - cFx) * t, cyT = cFy + (cTy - cFy) * t  // centroid(t)
    let ang = theta * t
    let co = cos(ang), si = sin(ang)        // forward R(theta*t)
    let coN = cos(theta), siN = sin(theta)  // R(-theta) via (coN, -siN)
    func xform(_ fa: CGPoint, _ fb: CGPoint) -> CGPoint {
        let ax = fa.x - cFx, ay = fa.y - cFy
        // to-residual de-rotated into from's frame: R(-theta) * (b - cT)
        let bx0 = fb.x - cTx, by0 = fb.y - cTy
        let bx = bx0 * coN + by0 * siN
        let by = -bx0 * siN + by0 * coN
        // lerp residual in shared frame, then rotate forward by theta*t
        let rx = ax + (bx - ax) * t
        let ry = ay + (by - ay) * t
        return CGPoint(x: cxT + (rx * co - ry * si), y: cyT + (rx * si + ry * co))
    }
    var out: [TokenCompanionMorphPathSegment] = []
    out.reserveCapacity(a.count)
    for i in 0..<a.count {
        switch (a[i], b[i]) {
        case let (.move(p1), .move(p2)): out.append(.move(xform(p1, p2)))
        case let (.line(p1), .line(p2)): out.append(.line(xform(p1, p2)))
        case let (.curve(to1, c1a, c2a), .curve(to2, c1b, c2b)):
            out.append(.curve(to: xform(to1, to2), c1: xform(c1a, c1b), c2: xform(c2a, c2b)))
        case let (.quad(to1, c1), .quad(to2, c2)):
            out.append(.quad(to: xform(to1, to2), c: xform(c1, c2)))
        case (.close, .close): out.append(.close)
        default: out.append(t < 0.5 ? a[i] : b[i])
        }
    }
    return out
}

// (No paths have per-state rotation transforms — MorphRotation omitted.)

// (No multi-subpath paths — RigidBody modifier omitted.)

// MARK: - Animatable shapes

// TRANSFORM-strategy morph: paths share the same command structure across
// all source states, so we lerp control points directly. Bezier curves are
// preserved exactly — the silhouette never goes polygonal.
struct TokenCompanionMorphShape: Shape {
    var from: [TokenCompanionMorphPathSegment]
    var to: [TokenCompanionMorphPathSegment]
    var progress: Double

    var animatableData: Double {
        get { progress }
        set { progress = newValue }
    }

    func path(in rect: CGRect) -> Path {
        Path(tokenCompanion: lerpSegments(from, to, progress))
    }
}

// MORPH-strategy morph: paths have different command structures across
// states (e.g. the snowman body, which redraws its silhouette between
// stress and joy). We pre-sample each state's path at export time into a
// uniform polygon (N points, evenly spaced along arc length), then lerp
// vertex-by-vertex. The resulting shape is polygonal — bezier curves are
// approximated by line segments — but the morph itself is smooth.
//
// AnimatablePair lets SwiftUI's animation system drive only progress;
// the polygon arrays themselves are static (resolved at compile time).
struct TokenCompanionMorphPolygonShape: Shape {
    var fromPoly: [CGPoint]
    var toPoly: [CGPoint]
    var progress: Double

    var animatableData: Double {
        get { progress }
        set { progress = newValue }
    }

    func path(in rect: CGRect) -> Path {
        var path = Path()
        let n = min(fromPoly.count, toPoly.count)
        guard n > 1 else { return path }
        let t = progress
        path.move(to: lerpP(fromPoly[0], toPoly[0], t))
        for i in 1..<n {
            path.addLine(to: lerpP(fromPoly[i], toPoly[i], t))
        }
        path.closeSubpath()
        return path
    }
}

// MARK: - Path data (parsed from source SVG at export time)

private enum PathData {
    static let body_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 13, y: 32)),
        .curve(to: CGPoint(x: 27, y: 13), c1: CGPoint(x: 13, y: 22), c2: CGPoint(x: 18, y: 15)),
        .curve(to: CGPoint(x: 49, y: 13), c1: CGPoint(x: 34, y: 11.5), c2: CGPoint(x: 42, y: 11.5)),
        .curve(to: CGPoint(x: 63, y: 32), c1: CGPoint(x: 58, y: 15), c2: CGPoint(x: 63, y: 22)),
        .curve(to: CGPoint(x: 48, y: 51), c1: CGPoint(x: 63, y: 42), c2: CGPoint(x: 57, y: 49)),
        .curve(to: CGPoint(x: 28, y: 51), c1: CGPoint(x: 41, y: 52.5), c2: CGPoint(x: 35, y: 52.5)),
        .curve(to: CGPoint(x: 13, y: 32), c1: CGPoint(x: 19, y: 49), c2: CGPoint(x: 13, y: 42)),
        .close
    ]
    static let body_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 13, y: 31)),
        .curve(to: CGPoint(x: 27, y: 12), c1: CGPoint(x: 13, y: 21), c2: CGPoint(x: 18, y: 14)),
        .curve(to: CGPoint(x: 49, y: 12), c1: CGPoint(x: 34, y: 10.5), c2: CGPoint(x: 42, y: 10.5)),
        .curve(to: CGPoint(x: 63, y: 31), c1: CGPoint(x: 58, y: 14), c2: CGPoint(x: 63, y: 21)),
        .curve(to: CGPoint(x: 48, y: 50), c1: CGPoint(x: 63, y: 41), c2: CGPoint(x: 57, y: 48)),
        .curve(to: CGPoint(x: 28, y: 50), c1: CGPoint(x: 41, y: 51.5), c2: CGPoint(x: 35, y: 51.5)),
        .curve(to: CGPoint(x: 13, y: 31), c1: CGPoint(x: 19, y: 48), c2: CGPoint(x: 13, y: 41)),
        .close
    ]
    static let earL_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 22, y: 16)),
        .curve(to: CGPoint(x: 20, y: 6), c1: CGPoint(x: 18, y: 13), c2: CGPoint(x: 18, y: 8)),
        .curve(to: CGPoint(x: 29, y: 13), c1: CGPoint(x: 22, y: 4), c2: CGPoint(x: 26, y: 8)),
        .close
    ]
    static let earL_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 22, y: 15)),
        .curve(to: CGPoint(x: 20, y: 5), c1: CGPoint(x: 18, y: 12), c2: CGPoint(x: 18, y: 7)),
        .curve(to: CGPoint(x: 29, y: 12), c1: CGPoint(x: 22, y: 3), c2: CGPoint(x: 26, y: 7)),
        .close
    ]
    static let earR_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 47, y: 13)),
        .curve(to: CGPoint(x: 56, y: 6), c1: CGPoint(x: 50, y: 8), c2: CGPoint(x: 54, y: 4)),
        .curve(to: CGPoint(x: 54, y: 16), c1: CGPoint(x: 58, y: 8), c2: CGPoint(x: 58, y: 13)),
        .close
    ]
    static let earR_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 47, y: 12)),
        .curve(to: CGPoint(x: 56, y: 5), c1: CGPoint(x: 50, y: 7), c2: CGPoint(x: 54, y: 3)),
        .curve(to: CGPoint(x: 54, y: 15), c1: CGPoint(x: 58, y: 7), c2: CGPoint(x: 58, y: 12)),
        .close
    ]
    static let eyeL_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 26.3, y: 30)),
        .curve(to: CGPoint(x: 28.5, y: 27), c1: CGPoint(x: 26.3, y: 28.34315), c2: CGPoint(x: 27.28497, y: 27)),
        .curve(to: CGPoint(x: 30.7, y: 30), c1: CGPoint(x: 29.71503, y: 27), c2: CGPoint(x: 30.7, y: 28.34315)),
        .curve(to: CGPoint(x: 28.5, y: 33), c1: CGPoint(x: 30.7, y: 31.65685), c2: CGPoint(x: 29.71503, y: 33)),
        .curve(to: CGPoint(x: 26.3, y: 30), c1: CGPoint(x: 27.28497, y: 33), c2: CGPoint(x: 26.3, y: 31.65685)),
        .close
    ]
    static let eyeL_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 26.3, y: 29)),
        .curve(to: CGPoint(x: 28.5, y: 28), c1: CGPoint(x: 26.3, y: 28.44772), c2: CGPoint(x: 27.28497, y: 28)),
        .curve(to: CGPoint(x: 30.7, y: 29), c1: CGPoint(x: 29.71503, y: 28), c2: CGPoint(x: 30.7, y: 28.44772)),
        .curve(to: CGPoint(x: 28.5, y: 30), c1: CGPoint(x: 30.7, y: 29.55228), c2: CGPoint(x: 29.71503, y: 30)),
        .curve(to: CGPoint(x: 26.3, y: 29), c1: CGPoint(x: 27.28497, y: 30), c2: CGPoint(x: 26.3, y: 29.55228)),
        .close
    ]
    static let eyeR_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 45.3, y: 30)),
        .curve(to: CGPoint(x: 47.5, y: 27), c1: CGPoint(x: 45.3, y: 28.34315), c2: CGPoint(x: 46.28497, y: 27)),
        .curve(to: CGPoint(x: 49.7, y: 30), c1: CGPoint(x: 48.71503, y: 27), c2: CGPoint(x: 49.7, y: 28.34315)),
        .curve(to: CGPoint(x: 47.5, y: 33), c1: CGPoint(x: 49.7, y: 31.65685), c2: CGPoint(x: 48.71503, y: 33)),
        .curve(to: CGPoint(x: 45.3, y: 30), c1: CGPoint(x: 46.28497, y: 33), c2: CGPoint(x: 45.3, y: 31.65685)),
        .close
    ]
    static let eyeR_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 45.3, y: 29)),
        .curve(to: CGPoint(x: 47.5, y: 28), c1: CGPoint(x: 45.3, y: 28.44772), c2: CGPoint(x: 46.28497, y: 28)),
        .curve(to: CGPoint(x: 49.7, y: 29), c1: CGPoint(x: 48.71503, y: 28), c2: CGPoint(x: 49.7, y: 28.44772)),
        .curve(to: CGPoint(x: 47.5, y: 30), c1: CGPoint(x: 49.7, y: 29.55228), c2: CGPoint(x: 48.71503, y: 30)),
        .curve(to: CGPoint(x: 45.3, y: 29), c1: CGPoint(x: 46.28497, y: 30), c2: CGPoint(x: 45.3, y: 29.55228)),
        .close
    ]
    static let cheekL_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 20.5, y: 37)),
        .curve(to: CGPoint(x: 23.5, y: 35.6), c1: CGPoint(x: 20.5, y: 36.2268), c2: CGPoint(x: 21.84315, y: 35.6)),
        .curve(to: CGPoint(x: 26.5, y: 37), c1: CGPoint(x: 25.15685, y: 35.6), c2: CGPoint(x: 26.5, y: 36.2268)),
        .curve(to: CGPoint(x: 23.5, y: 38.4), c1: CGPoint(x: 26.5, y: 37.7732), c2: CGPoint(x: 25.15685, y: 38.4)),
        .curve(to: CGPoint(x: 20.5, y: 37), c1: CGPoint(x: 21.84315, y: 38.4), c2: CGPoint(x: 20.5, y: 37.7732)),
        .close
    ]
    static let cheekL_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 20.3, y: 36)),
        .curve(to: CGPoint(x: 23.5, y: 34.4), c1: CGPoint(x: 20.3, y: 35.11634), c2: CGPoint(x: 21.73269, y: 34.4)),
        .curve(to: CGPoint(x: 26.7, y: 36), c1: CGPoint(x: 25.26731, y: 34.4), c2: CGPoint(x: 26.7, y: 35.11634)),
        .curve(to: CGPoint(x: 23.5, y: 37.6), c1: CGPoint(x: 26.7, y: 36.88366), c2: CGPoint(x: 25.26731, y: 37.6)),
        .curve(to: CGPoint(x: 20.3, y: 36), c1: CGPoint(x: 21.73269, y: 37.6), c2: CGPoint(x: 20.3, y: 36.88366)),
        .close
    ]
    static let cheekR_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 49.5, y: 37)),
        .curve(to: CGPoint(x: 52.5, y: 35.6), c1: CGPoint(x: 49.5, y: 36.2268), c2: CGPoint(x: 50.84315, y: 35.6)),
        .curve(to: CGPoint(x: 55.5, y: 37), c1: CGPoint(x: 54.15685, y: 35.6), c2: CGPoint(x: 55.5, y: 36.2268)),
        .curve(to: CGPoint(x: 52.5, y: 38.4), c1: CGPoint(x: 55.5, y: 37.7732), c2: CGPoint(x: 54.15685, y: 38.4)),
        .curve(to: CGPoint(x: 49.5, y: 37), c1: CGPoint(x: 50.84315, y: 38.4), c2: CGPoint(x: 49.5, y: 37.7732)),
        .close
    ]
    static let cheekR_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 49.3, y: 36)),
        .curve(to: CGPoint(x: 52.5, y: 34.4), c1: CGPoint(x: 49.3, y: 35.11634), c2: CGPoint(x: 50.73269, y: 34.4)),
        .curve(to: CGPoint(x: 55.7, y: 36), c1: CGPoint(x: 54.26731, y: 34.4), c2: CGPoint(x: 55.7, y: 35.11634)),
        .curve(to: CGPoint(x: 52.5, y: 37.6), c1: CGPoint(x: 55.7, y: 36.88366), c2: CGPoint(x: 54.26731, y: 37.6)),
        .curve(to: CGPoint(x: 49.3, y: 36), c1: CGPoint(x: 50.73269, y: 37.6), c2: CGPoint(x: 49.3, y: 36.88366)),
        .close
    ]
    static let mouth_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 34, y: 37)),
        .curve(to: CGPoint(x: 42, y: 37), c1: CGPoint(x: 36, y: 39.5), c2: CGPoint(x: 40, y: 39.5))
    ]
    static let mouth_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 33, y: 36)),
        .curve(to: CGPoint(x: 43, y: 36), c1: CGPoint(x: 35.5, y: 41), c2: CGPoint(x: 40.5, y: 41))
    ]
    static let footL_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 25, y: 48)),
        .curve(to: CGPoint(x: 29, y: 54), c1: CGPoint(x: 24, y: 52), c2: CGPoint(x: 25, y: 54)),
        .curve(to: CGPoint(x: 32, y: 49), c1: CGPoint(x: 32, y: 54), c2: CGPoint(x: 33, y: 52)),
        .close
    ]
    static let footL_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 25, y: 47)),
        .curve(to: CGPoint(x: 29, y: 53), c1: CGPoint(x: 24, y: 51), c2: CGPoint(x: 25, y: 53)),
        .curve(to: CGPoint(x: 32, y: 48), c1: CGPoint(x: 32, y: 53), c2: CGPoint(x: 33, y: 51)),
        .close
    ]
    static let footR_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 44, y: 49)),
        .curve(to: CGPoint(x: 47, y: 54), c1: CGPoint(x: 43, y: 52), c2: CGPoint(x: 44, y: 54)),
        .curve(to: CGPoint(x: 51, y: 48), c1: CGPoint(x: 51, y: 54), c2: CGPoint(x: 52, y: 52)),
        .close
    ]
    static let footR_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 44, y: 48)),
        .curve(to: CGPoint(x: 47, y: 53), c1: CGPoint(x: 43, y: 51), c2: CGPoint(x: 44, y: 53)),
        .curve(to: CGPoint(x: 51, y: 47), c1: CGPoint(x: 51, y: 53), c2: CGPoint(x: 52, y: 51)),
        .close
    ]
    static let armL_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 14, y: 32)),
        .curve(to: CGPoint(x: 11, y: 38), c1: CGPoint(x: 10, y: 33), c2: CGPoint(x: 9, y: 36))
    ]
    static let armL_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 14, y: 31)),
        .curve(to: CGPoint(x: 10, y: 35), c1: CGPoint(x: 10, y: 30), c2: CGPoint(x: 8, y: 32))
    ]
    static let armR_idle_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 62, y: 32)),
        .curve(to: CGPoint(x: 65, y: 38), c1: CGPoint(x: 66, y: 33), c2: CGPoint(x: 67, y: 36))
    ]
    static let armR_happy_sub0: [TokenCompanionMorphPathSegment] = [
        .move(CGPoint(x: 62, y: 31)),
        .curve(to: CGPoint(x: 66, y: 35), c1: CGPoint(x: 66, y: 30), c2: CGPoint(x: 68, y: 32))
    ]
}

// MARK: - Per-state lookup

// Strategy assignments (path-command structure + preview method overrides):
//   TRANSFORM (12): body, earL, earR, eyeL, eyeR, cheekL, cheekR, mouth, footL, footR, armL, armR
//   MORPH     (0):

// Subpath counts per id (most are 1; stroke paths like hands have N).
private func subpathCount(forId id: String) -> Int {
    switch id {
    case "body": return 1
    case "earL": return 1
    case "earR": return 1
    case "eyeL": return 1
    case "eyeR": return 1
    case "cheekL": return 1
    case "cheekR": return 1
    case "mouth": return 1
    case "footL": return 1
    case "footR": return 1
    case "armL": return 1
    case "armR": return 1
    default: return 1
    }
}

// Subpath-aware segment lookup. For each (id, subpathIndex, state) returns
// the parsed segments to feed into TokenCompanionMorphShape. Out-of-range subpaths return [].
private func segments(for id: String, subpath s: Int, in state: TokenCompanionState) -> [TokenCompanionMorphPathSegment] {
    switch (id, s, state) {
    case ("body", 0, .idle): return PathData.body_idle_sub0
    case ("body", 0, .happy): return PathData.body_happy_sub0
    case ("earL", 0, .idle): return PathData.earL_idle_sub0
    case ("earL", 0, .happy): return PathData.earL_happy_sub0
    case ("earR", 0, .idle): return PathData.earR_idle_sub0
    case ("earR", 0, .happy): return PathData.earR_happy_sub0
    case ("eyeL", 0, .idle): return PathData.eyeL_idle_sub0
    case ("eyeL", 0, .happy): return PathData.eyeL_happy_sub0
    case ("eyeR", 0, .idle): return PathData.eyeR_idle_sub0
    case ("eyeR", 0, .happy): return PathData.eyeR_happy_sub0
    case ("cheekL", 0, .idle): return PathData.cheekL_idle_sub0
    case ("cheekL", 0, .happy): return PathData.cheekL_happy_sub0
    case ("cheekR", 0, .idle): return PathData.cheekR_idle_sub0
    case ("cheekR", 0, .happy): return PathData.cheekR_happy_sub0
    case ("mouth", 0, .idle): return PathData.mouth_idle_sub0
    case ("mouth", 0, .happy): return PathData.mouth_happy_sub0
    case ("footL", 0, .idle): return PathData.footL_idle_sub0
    case ("footL", 0, .happy): return PathData.footL_happy_sub0
    case ("footR", 0, .idle): return PathData.footR_idle_sub0
    case ("footR", 0, .happy): return PathData.footR_happy_sub0
    case ("armL", 0, .idle): return PathData.armL_idle_sub0
    case ("armL", 0, .happy): return PathData.armL_happy_sub0
    case ("armR", 0, .idle): return PathData.armR_idle_sub0
    case ("armR", 0, .happy): return PathData.armR_happy_sub0
    default: return []
    }
}

private func polygon(for id: String, in state: TokenCompanionState) -> [CGPoint] {
    switch (id, state) {
    default: return []
    }
}

// Returns true if this shared id uses the polygon (MORPH) renderer.
private func isPolyMorph(_ id: String) -> Bool {
    return false
}




// MARK: - Orphan decorations (per-state non-morphing shapes)

// Orphans are decorative shapes that exist in only some states (e.g. the
// ice-cube background in state-1, the flowers in state-5). They don't morph
// — they appear when their state is the displayed state, hidden otherwise.
// Transforms are baked into path data at export time. Gradient fills are
// emitted as proper SwiftUI RadialGradient/LinearGradient with bbox-
// normalized centers (best-effort — SwiftUI's gradient model can't fully
// replicate arbitrary SVG gradientTransform matrices).

@ViewBuilder private func backOrphans(for state: TokenCompanionState, t: Double, amplitude: Double) -> some View {
    switch state {
    case .idle:
        EmptyView()
    case .happy:
        EmptyView()
    }
}

@ViewBuilder private func frontOrphans(for state: TokenCompanionState, t: Double, amplitude: Double) -> some View {
    switch state {
    case .idle:
        EmptyView()
    case .happy:
        EmptyView()
    }
}

// MARK: - Idle animations

// One TokenCompanionIdlePart per concurrent motion within a state. The Swift idle layer
// uses sin(t * 2π / duration) just like the JS engine, scaled by amplitude
// and the live amplitude (which we ramp during morphs).
struct TokenCompanionIdlePart {
    var kind: String                     // "sway", "breathe-y", "rotate-around-point", "waggle-sequence"
    var duration: Double = 1.5
    var amplitude: Double = 2.0
    var pivot: CGPoint? = nil            // for rotate-around-point
    var anchor: UnitPoint? = nil         // pivot override (authored origin / preview anchor card); nil → kind default
    var selector: String? = nil          // logical id like "handl" (no "#path-" prefix here)
    var cycleDuration: Double = 4.5      // for waggle-sequence
    var restFraction: Double = 0.25      // for waggle-sequence
    var gateCycle: Double? = nil         // optional gate (sec)
    var gateRange: ClosedRange<Double>? = nil    // [0..1] of gate cycle when active
    var gateFade: Double = 0.05
    // "float" (buoyant flight) params:
    var baseLift: Double = 0             // raised baseline (flies higher)
    var asymmetry: Double = 0.5          // fraction of the cycle spent descending (slow fall)
    var floatRotate: Double = 0          // body-tilt amplitude (deg)
    var rotateDuration: Double = 0       // 0 → derive from duration
    var drift: Double = 0                // horizontal sway amplitude (px)
    var driftDuration: Double = 0        // 0 → derive from duration
}

private func idleParts(for state: TokenCompanionState) -> [TokenCompanionIdlePart] {
    switch state {
    case .idle: return [
        TokenCompanionIdlePart(kind: "breathe-y", duration: 3.8, amplitude: 0.018, anchor: UnitPoint(x: 0.5, y: 0.87931))
    ]
    case .happy: return [
        TokenCompanionIdlePart(kind: "bob", duration: 1.5, amplitude: 1.5, anchor: UnitPoint(x: 0.5, y: 0.87931))
    ]
    }
}

// Each part evaluates to a CGAffineTransform applied via .modifier on the
// matching layer. Whole-character parts (sway, breathe-y, waggle-sequence)
// have selector == nil and target the root. rotate-around-point has a
// selector and targets that named child.
struct TokenCompanionIdleTransform {
    var translation: CGSize = .zero
    var rotationDegrees: Double = 0
    var scale: CGSize = CGSize(width: 1, height: 1)
    var anchor: UnitPoint = UnitPoint(x: 0.5, y: 1.0)  // bottom-center default
    var pivotAbsolute: CGPoint? = nil                  // for rotate-around-point
}

// easeInOutSine in [0, 1]
private func easeInOutSine(_ t: Double) -> Double { -(cos(.pi * t) - 1) / 2 }

// NOTE: per-element idle (selectorAll / selector parts — wing flaps, blink,
// spin, drip, nod sub-groups, pop-loop) is handled by idleForElement and the
// TokenCompanionElementIdleMod modifier in the "Per-element idle" section below, which
// returns a FULL transform (offset + rotation + scale + squish + opacity),
// not just a rotation. evaluateIdle here drives only WHOLE-BODY root parts.

private func evaluateIdle(_ part: TokenCompanionIdlePart, t: Double, amplitude: Double) -> TokenCompanionIdleTransform {
    var x = TokenCompanionIdleTransform()
    let amp = amplitude
    switch part.kind {
    case "sway":
        x.rotationDegrees = part.amplitude * amp * sin(t * 2 * .pi / part.duration)
    case "breathe":
        let v = 1 + part.amplitude * amp * (0.5 + 0.5 * sin(t * 2 * .pi / part.duration))
        x.scale = CGSize(width: v, height: v)
    case "breathe-y":
        let v = 1 + part.amplitude * amp * sin(t * 2 * .pi / part.duration)
        x.scale = CGSize(width: 1, height: v)
    case "bob":
        x.translation = CGSize(width: 0, height: -part.amplitude * amp * (0.5 + 0.5 * sin(t * 2 * .pi / part.duration)))
    case "nod":
        // Whole-body head-raise: rises from baseline (0 → up → 0), never dips.
        x.translation = CGSize(width: 0, height: -part.amplitude * amp * (0.5 - 0.5 * cos(t * 2 * .pi / part.duration)))
    case "shake":
        x.rotationDegrees = part.amplitude * amp * sin(t * 2 * .pi / part.duration)
    case "waggle-sequence":
        let cycle = part.cycleDuration
        let A = part.amplitude
        let rest = part.restFraction
        let motion = 1 - rest
        let TOTAL = 12.8
        let u = motion / TOTAL
        let rampLeftEnd = 4 * u
        let holdLeftEnd = rampLeftEnd + 0.4 * u
        let rampToRightEnd = holdLeftEnd + 4 * u
        let holdRightEnd = rampToRightEnd + 0.4 * u
        let rampBackEnd = motion
        let phase = (t.truncatingRemainder(dividingBy: cycle)) / cycle
        var angle = 0.0
        if phase < rampLeftEnd {
            angle = -A * easeInOutSine(phase / rampLeftEnd)
        } else if phase < holdLeftEnd {
            angle = -A
        } else if phase < rampToRightEnd {
            angle = -A + 2 * A * easeInOutSine((phase - holdLeftEnd) / (rampToRightEnd - holdLeftEnd))
        } else if phase < holdRightEnd {
            angle = A
        } else if phase < rampBackEnd {
            angle = A * (1 - easeInOutSine((phase - holdRightEnd) / (rampBackEnd - holdRightEnd)))
        }
        x.rotationDegrees = angle * amp
    case "rotate-around-point":
        var gateAmp = 1.0
        if let gateCycle = part.gateCycle, let gateRange = part.gateRange {
            let gPhase = (t.truncatingRemainder(dividingBy: gateCycle)) / gateCycle
            let from = gateRange.lowerBound
            let to = gateRange.upperBound
            let fade = part.gateFade
            if gPhase < from || gPhase > to { gateAmp = 0 }
            else if gPhase < from + fade { gateAmp = easeInOutSine((gPhase - from) / fade) }
            else if gPhase > to - fade { gateAmp = easeInOutSine((to - gPhase) / fade) }
        }
        x.rotationDegrees = part.amplitude * amp * gateAmp * sin(t * 2 * .pi / part.duration)
        x.pivotAbsolute = part.pivot
    case "float":
        // Buoyant flight (ported from the JS engine): a raised baseline plus an
        // asymmetric vertical bob (quick rise, slow fall), a gentle horizontal
        // drift, and a slight body tilt — incommensurate periods so it never
        // quite repeats. Whole-body, anchored at center (matches origin 50% 50%).
        let d = part.duration
        let rotDur = part.rotateDuration > 0 ? part.rotateDuration : d * 1.7
        let driftDur = part.driftDuration > 0 ? part.driftDuration : d * 1.3
        let phase = (t.truncatingRemainder(dividingBy: d)) / d
        let rise = max(0.05, 1 - part.asymmetry)
        let h = phase < rise
            ? easeInOutSine(phase / rise)
            : 1 - easeInOutSine((phase - rise) / part.asymmetry)
        let ty = -(part.baseLift + part.amplitude * h) * amp
        let tx = part.drift * amp * sin(t * 2 * .pi / driftDur)
        x.translation = CGSize(width: tx, height: ty)
        x.rotationDegrees = part.floatRotate * amp * sin(t * 2 * .pi / rotDur)
        x.anchor = UnitPoint(x: 0.5, y: 0.5)
    default:
        break
    }
    // An explicit anchor (authored part origin or the preview's idle-anchor
    // anchor override) wins over the kind's default pivot — matches the JS
    // engine's originOverride precedence.
    if let a = part.anchor { x.anchor = a }
    return x
}

// MARK: - Per-element idle

// A composed idle transform for ONE element (shared path or orphan). Mirrors
// the JS engine's per-element style.transform / style.opacity writes: an
// offset, a rotation about an anchor, a scale about an anchor, an appended
// vertical blink squish, and an optional opacity (when the part owns it).
struct TokenCompanionElementIdle {
    var offset: CGSize = .zero
    var preRotOffset: CGSize = .zero     // translate applied BEFORE the rotation (so it rotates with it)
    var rotationDeg: Double = 0
    var rotAnchor: UnitPoint = .center
    var scaleX: Double = 1
    var scaleY: Double = 1
    var scaleAnchor: UnitPoint = .center
    var blinkScaleY: Double = 1
    var blinkAnchor: UnitPoint = .center
    var opacity: Double = 1
    var setsOpacity: Bool = false
}

// easeOutBack overshoot — matches the JS engine's easeFns.easeOutBack.
private func easeOutBack(_ t: Double) -> Double {
    let c1 = 1.70158, c3 = 1.70158 + 1
    return 1 + c3 * pow(t - 1, 3) + c1 * pow(t - 1, 2)
}

// Applies the composed TokenCompanionElementIdle. Modifier order matches the CSS transform
// list the engine builds: blink squish is innermost (applied first in
// element-local space), then base scale/rotation, then translate; opacity
// (drip / pop-loop / star cycle) multiplies the element's own opacity.
struct TokenCompanionElementIdleMod: ViewModifier {
    let e: TokenCompanionElementIdle
    func body(content: Content) -> some View {
        content
            .scaleEffect(x: 1, y: e.blinkScaleY, anchor: e.blinkAnchor)
            .scaleEffect(x: e.scaleX, y: e.scaleY, anchor: e.scaleAnchor)
            .offset(e.preRotOffset)   // BEFORE rotation → rotates with it (matches CSS "rotate() translate()")
            .rotationEffect(.degrees(e.rotationDeg), anchor: e.rotAnchor)
            .offset(e.offset)
            .opacity(e.setsOpacity ? e.opacity : 1)
    }
}

// --- per-kind contributions (ported from the JS IdleAnimator) ---

private func applySwayEl(_ e: inout TokenCompanionElementIdle, amplitude: Double, duration: Double, t: Double, amp: Double) {
    e.rotationDeg += amplitude * amp * sin(t * 2 * .pi / duration)
    e.rotAnchor = UnitPoint(x: 0.5, y: 1.0)   // bottom-center
}

private func applyNod(_ e: inout TokenCompanionElementIdle, amplitude: Double, duration: Double, t: Double, amp: Double) {
    e.offset.height += -amplitude * amp * (0.5 - 0.5 * cos(t * 2 * .pi / duration))
}

private func rotPointGate(t: Double, gateCycle: Double, from: Double, to: Double, fade: Double) -> Double {
    let g = (t.truncatingRemainder(dividingBy: gateCycle)) / gateCycle
    if g < from || g > to { return 0 }
    if g < from + fade { return easeInOutSine((g - from) / fade) }
    if g > to - fade { return easeInOutSine((to - g) / fade) }
    return 1
}

private func applyRotPoint(_ e: inout TokenCompanionElementIdle, pivotX: Double, pivotY: Double, amplitude: Double, duration: Double, phase: Double, bias: Double, liftUndo: Double, counterSwayAngle: Double, gateAmp: Double, t: Double, amp: Double, canvasW: Double, canvasH: Double) {
    // bias: constant rotation offset (e.g. resting a wing down / flapping back
    // up); liftUndo: amp-scaled downward translate that cancels a baked vertical
    // lift so the flap lands at the un-lifted position at full amplitude.
    let flap = (amplitude * gateAmp * sin(t * 2 * .pi / duration + phase) + bias) * amp
    e.rotationDeg += (flap - counterSwayAngle)
    e.rotAnchor = UnitPoint(x: pivotX / canvasW, y: pivotY / canvasH)
    // PRE-rotation offset: the JS engine applies liftUndo as `translate()` INSIDE
    // `rotate()`, so the baked lift cancels cleanly. Applying it after the rotation
    // (a plain .offset) would leave the wing displaced sideways by ~lift·sin(angle).
    e.preRotOffset.height += liftUndo * amp
}

private func applyBlink(_ e: inout TokenCompanionElementIdle, center: CGPoint, period: Double, blinkDur: Double, minScale: Double, t: Double, amp: Double, canvasW: Double, canvasH: Double) {
    let ph = t.truncatingRemainder(dividingBy: period)
    var sy = 1.0
    if ph > period - blinkDur {
        let u = (ph - (period - blinkDur)) / blinkDur
        sy = 1 - (1 - minScale) * sin(u * .pi)
    }
    sy = 1 - (1 - sy) * amp
    e.blinkScaleY *= sy
    e.blinkAnchor = UnitPoint(x: center.x / canvasW, y: center.y / canvasH)
}

private func applySpin(_ e: inout TokenCompanionElementIdle, index: Int, center: CGPoint, duration: Double, direction: Double, stagger: Double, alternate: Bool, t: Double, canvasW: Double, canvasH: Double) {
    let edir = (alternate && index % 2 == 1) ? -direction : direction
    let angle = (edir * ((t + Double(index) * stagger) / duration) * 360).truncatingRemainder(dividingBy: 360)
    e.rotationDeg += angle
    e.rotAnchor = UnitPoint(x: center.x / canvasW, y: center.y / canvasH)
}

private func applyDrip(_ e: inout TokenCompanionElementIdle, originX: Double, originY: Double, riseMs: Double, holdMs: Double, fallMs: Double, restMs: Double, fallDist: Double, riseScale: Double, t: Double, amp: Double, canvasW: Double, canvasH: Double) {
    let cycleMs = riseMs + holdMs + fallMs + restMs
    let ph = (t * 1000).truncatingRemainder(dividingBy: cycleMs)
    var opacity = 0.0, ty = 0.0, scale = riseScale
    if ph < riseMs {
        let eased = easeInOutSine(ph / riseMs)
        opacity = eased; ty = 0; scale = riseScale + (1 - riseScale) * eased
    } else if ph < riseMs + holdMs {
        opacity = 1; ty = 0; scale = 1
    } else if ph < riseMs + holdMs + fallMs {
        let eased = easeInOutSine((ph - riseMs - holdMs) / fallMs)
        opacity = 1 - eased; ty = fallDist * eased; scale = 1
    } else {
        opacity = 0; ty = 0; scale = riseScale
    }
    e.offset.height += ty
    e.scaleX *= scale; e.scaleY *= scale
    e.scaleAnchor = UnitPoint(x: originX / canvasW, y: originY / canvasH)
    e.opacity *= opacity * amp; e.setsOpacity = true
}

private func applyPopLoop(_ e: inout TokenCompanionElementIdle, phaseOffset: Double, cycle: Double, visFrac: Double, fadeFrac: Double, sFrom: Double, sTo: Double, rFrom: Double, rTo: Double, txFrom: Double, tyFrom: Double, txTo: Double, tyTo: Double, originX: Double, originY: Double, t: Double, amp: Double, canvasW: Double, canvasH: Double) {
    var phase = (t / cycle + phaseOffset).truncatingRemainder(dividingBy: 1)
    if phase < 0 { phase += 1 }
    var opacity = 0.0, scale = sFrom, rot = rFrom, tx = txFrom, ty = tyFrom
    let visStart = fadeFrac, visEnd = fadeFrac + visFrac, fadeOutEnd = fadeFrac + visFrac + fadeFrac
    if phase < visStart {
        let u = phase / fadeFrac
        opacity = u; scale = sFrom + (sTo - sFrom) * easeOutBack(u)
        rot = rFrom; tx = txFrom; ty = tyFrom
    } else if phase < visEnd {
        let u = (phase - visStart) / visFrac
        opacity = 1; scale = sTo
        rot = rFrom + (rTo - rFrom) * u
        tx = txFrom + (txTo - txFrom) * u
        ty = tyFrom + (tyTo - tyFrom) * u
    } else if phase < fadeOutEnd {
        let u = (phase - visEnd) / fadeFrac
        opacity = 1 - u; scale = sTo - (sTo - sFrom) * u
        rot = rTo; tx = txTo; ty = tyTo
    }
    e.offset.width += tx; e.offset.height += ty
    e.scaleX *= scale; e.scaleY *= scale
    e.rotationDeg += rot
    let a = UnitPoint(x: originX / canvasW, y: originY / canvasH)
    e.scaleAnchor = a; e.rotAnchor = a
    e.opacity *= opacity * amp; e.setsOpacity = true
}

// Looping star burst (state-level orphanPopLoop): each star pops in (back-out
// overshoot, staggered), holds, then drifts outward along its radial + shrinks
// while fading, then rests — all derived as one continuous phase of t.
private func applyOrphanPopLoop(_ e: inout TokenCompanionElementIdle, index: Int, count: Int, center: CGPoint, radial: CGPoint, popDur: Double, stagger: Double, holdMs: Double, fadeMs: Double, restMs: Double, travel: Double, endScale: Double, t: Double, canvasW: Double, canvasH: Double) {
    let appearTotal = popDur + Double(count) * stagger
    let exitTotal = fadeMs + Double(count) * stagger
    let period = appearTotal + holdMs + exitTotal + restMs
    let ph = (t * 1000).truncatingRemainder(dividingBy: period)
    let aStart = Double(index) * stagger, aEnd = aStart + popDur
    let dStart = appearTotal + holdMs + Double(index) * stagger, dEnd = dStart + fadeMs
    var opacity = 0.0, scale = 1.0, tx = 0.0, ty = 0.0
    var anchor = UnitPoint(x: 0.5, y: 0.5)   // "50%" = view-box center during appear/hold
    if ph >= aStart && ph < aEnd {
        let u = (ph - aStart) / popDur
        opacity = min(1.0, u * 1.6)
        scale = 0.3 + 0.7 * easeOutBack(u)
    } else if ph >= aEnd && ph < dStart {
        opacity = 1; scale = 1
    } else if ph >= dStart && ph < dEnd {
        let m = easeInOutSine((ph - dStart) / fadeMs)
        tx = radial.x * travel * m; ty = radial.y * travel * m
        scale = 1 + (endScale - 1) * m
        opacity = 1 - m
        anchor = UnitPoint(x: center.x / canvasW, y: center.y / canvasH)
    }
    e.offset.width += tx; e.offset.height += ty
    e.scaleX *= scale; e.scaleY *= scale
    e.scaleAnchor = anchor
    e.opacity *= opacity; e.setsOpacity = true
}

// Per-element idle dispatch: returns the composed TokenCompanionElementIdle for a given
// shared-path or orphan id in a state. Identity when nothing targets it.
private func idleForElement(_ id: String, in state: TokenCompanionState, t: Double, amplitude: Double, blinkSuppressed: Bool = false) -> TokenCompanionElementIdle {
    var e = TokenCompanionElementIdle()
    let amp = amplitude
    switch state {
    case .idle:
        if !blinkSuppressed, let mi = ["eyeL", "eyeR"].firstIndex(of: id) {
            let centers: [CGPoint] = [CGPoint(x: 28.5, y: 30), CGPoint(x: 47.5, y: 30)]
            applyBlink(&e, center: centers[mi], period: 4.6, blinkDur: 0.16, minScale: 0.12, t: t, amp: amp, canvasW: 76, canvasH: 58)
        }
    case .happy:
        if !blinkSuppressed, let mi = ["eyeL", "eyeR"].firstIndex(of: id) {
            let centers: [CGPoint] = [CGPoint(x: 28.5, y: 29), CGPoint(x: 47.5, y: 29)]
            applyBlink(&e, center: centers[mi], period: 4.6, blinkDur: 0.16, minScale: 0.12, t: t, amp: amp, canvasW: 76, canvasH: 58)
        }
    }
    return e
}

// MARK: - Particles

struct TokenCompanionParticleSpec {
    var center: CGPoint
    var radius: ClosedRange<Double>
    var angleRangeDeg: ClosedRange<Double>     // SVG convention: 0°=right, 90°=down
    var driftX: ClosedRange<Double>
    var driftY: ClosedRange<Double>
    var scale: ClosedRange<Double>
    var lifetime: Double                      // ms
    var lifetimeJitter: Double                // ms
    var interval: Double                      // ms between spawns
    var burst: Int
    var rotationJitterDeg: Double
}

private func particleSpec(for state: TokenCompanionState) -> TokenCompanionParticleSpec? {
    switch state {
    case .idle: return nil
    case .happy: return nil
    }
}

// MARK: - Particle templates

// Each top-level <g> in an orphanSVG of a state-with-particles becomes
// one ParticleTemplate. The HTML preview clones these groups per spawn
// to emit live flower copies; in Swift we render each group to a UIImage
// once and feed it as a CAEmitterCell.contents. Multiple cells let the
// emitter randomly spawn each flower variant.
#if canImport(UIKit)
// ParticleTemplate is fileprivate because it's used as a parameter on
// TokenCompanionParticleLayerView (which is internal). Swift requires the type to be
// at least as accessible as the property/init using it.
fileprivate struct ParticleTemplate {
    let imageMaker: () -> UIImage
    let intrinsicSize: CGSize
}

fileprivate func particleTemplates(for state: TokenCompanionState) -> [ParticleTemplate] {
    switch state {
    case .idle: return []
    case .happy: return []
    }
}
#endif

#if canImport(UIKit)
// SwiftUI-native particle emitter. Replaces an earlier CAEmitterLayer
// implementation that couldn't faithfully reproduce the HTML preview's
// behavior — CAEmitterLayer can't spawn on a polar arc (it spawns in a
// full disk), can't animate alpha 0→1→0 (only a constant alphaSpeed),
// and its renderMode required tuning per character.
//
// This implementation matches the JS engine's ParticleSystem 1:1:
//   - Polar arc spawn: random angle in spawnArc.angle, random radius in
//     spawnArc.radius, converted to (x, y) via cos/sin around center.
//   - 4-keyframe lifetime: opacity 0 → 1 → 0.85 → 0; scale 0.4·from → to
//     → midpoint → 0.7·from; drift 0 → 20% → 60% → 100%.
//   - Normal alpha compositing (no additive blending).
//   - Timer-driven spawn with initial burst.
//   - Emission gate halts new spawns immediately when set false; alive
//     particles continue their lifetime naturally.

// Live particle data. Created in spawnOne, ages out when elapsed >= lifetime.
fileprivate struct ParticleAlive: Identifiable {
    let id = UUID()
    let templateIndex: Int
    let spawnX: Double
    let spawnY: Double
    let driftX: Double
    let driftY: Double
    let scaleFrom: Double         // base scale at endpoints
    let scaleTo: Double           // peak scale at the opacity peak
    let rotationEndDeg: Double    // final rotation; lerped from 0
    let lifetimeSec: Double
    let bornAt: Date
}

struct TokenCompanionParticleLayerView: View {
    let spec: TokenCompanionParticleSpec
    let imageMakers: [() -> UIImage]   // one per particle variant
    let emitting: Bool                 // false = stop new spawns (alive ones continue)
    let canvasW: Double
    let canvasH: Double

    @State private var particles: [ParticleAlive] = []
    @State private var spawnTimer: Timer?
    @State private var burstDone = false
    // Memoized images — rendered once on appear, reused per frame.
    // Without this we'd re-render each flower's bitmap on every TimelineView
    // tick (60 Hz × N alive particles).
    @State private var images: [UIImage] = []

    var body: some View {
        // TimelineView re-evaluates body on the system's animation timeline
        // (~60 fps). We compute each alive particle's interpolated position,
        // scale, opacity, and rotation from its bornAt timestamp + the current
        // context.date — no @State writes per frame, so layout stays cheap.
        TimelineView(.animation) { context in
            let now = context.date
            ZStack {
                ForEach(particles) { p in
                    particleView(p, now: now)
                }
            }
        }
        .frame(width: canvasW, height: canvasH)
        .onAppear {
            if images.isEmpty { images = imageMakers.map { $0() } }
            startEmitting()
        }
        .onDisappear { stopEmitting() }
        .onChange(of: emitting) { _, newValue in
            if newValue { startEmitting() } else { stopEmitting() }
        }
    }

    @ViewBuilder
    private func particleView(_ p: ParticleAlive, now: Date) -> some View {
        let elapsed = now.timeIntervalSince(p.bornAt)
        let t = min(max(elapsed / p.lifetimeSec, 0), 1)
        let (opacity, scale, driftFrac, rotFrac) = interpolateLifecycle(t: t, sFrom: p.scaleFrom, sTo: p.scaleTo)
        if opacity > 0 {
            let x = p.spawnX + p.driftX * driftFrac
            let y = p.spawnY + p.driftY * driftFrac
            Image(uiImage: images.indices.contains(p.templateIndex) ? images[p.templateIndex] : imageMakers[p.templateIndex]())
                .scaleEffect(scale)
                .rotationEffect(.degrees(p.rotationEndDeg * rotFrac))
                .opacity(opacity)
                .position(x: x, y: y)
                .allowsHitTesting(false)
        }
    }

    // Four-keyframe lifecycle interpolation — matches the JS engine's CSS
    // keyframe animation precisely. Linear segments between keyframes.
    //   t=0.00: opacity 0,    scale 0.4·from, drift 0%,   rot 0%
    //   t=0.18: opacity 1,    scale to,       drift 20%,  rot 25%
    //   t=0.65: opacity 0.85, scale midpoint, drift 60%,  rot 70%
    //   t=1.00: opacity 0,    scale 0.7·from, drift 100%, rot 100%
    private func interpolateLifecycle(t: Double, sFrom: Double, sTo: Double) -> (opacity: Double, scale: Double, driftFrac: Double, rotFrac: Double) {
        let sMid = (sFrom + sTo) / 2
        func lerpKeys(_ keys: [(Double, Double)]) -> Double {
            if t <= keys[0].0 { return keys[0].1 }
            if t >= keys.last!.0 { return keys.last!.1 }
            for i in 0..<(keys.count - 1) {
                if t <= keys[i + 1].0 {
                    let local = (t - keys[i].0) / (keys[i + 1].0 - keys[i].0)
                    return keys[i].1 + (keys[i + 1].1 - keys[i].1) * local
                }
            }
            return keys.last!.1
        }
        let opacity = lerpKeys([(0, 0), (0.18, 1), (0.65, 0.85), (1, 0)])
        let scale   = lerpKeys([(0, sFrom * 0.4), (0.18, sTo), (0.65, sMid), (1, sFrom * 0.7)])
        let drift   = lerpKeys([(0, 0), (0.18, 0.2), (0.65, 0.6), (1, 1.0)])
        let rot     = lerpKeys([(0, 0), (0.18, 0.25), (0.65, 0.7), (1, 1.0)])
        return (opacity, scale, drift, rot)
    }

    private func startEmitting() {
        guard emitting, !imageMakers.isEmpty else { return }
        if !burstDone {
            burstDone = true
            // Initial burst — spawn spec.burst particles immediately,
            // staggered slightly so they don't all pop in on the same frame.
            for i in 0..<spec.burst {
                let delay = Double(i) * min(0.12, spec.interval / 1000 / 2)
                DispatchQueue.main.asyncAfter(deadline: .now() + delay) {
                    spawnOne()
                }
            }
        }
        // Periodic spawn at spec.interval (ms).
        spawnTimer?.invalidate()
        spawnTimer = Timer.scheduledTimer(withTimeInterval: spec.interval / 1000, repeats: true) { _ in
            spawnOne()
        }
    }

    private func stopEmitting() {
        spawnTimer?.invalidate()
        spawnTimer = nil
        // Alive particles continue their lifecycle naturally — we do NOT
        // remove them. The TimelineView body ages each one out via opacity=0
        // once t ≥ 1, and the GC step below drops it from state.
    }

    private func spawnOne() {
        guard !imageMakers.isEmpty else { return }
        // Polar arc spawn — matches the JS engine's spawnArc semantics:
        // random angle in [angleMin, angleMax] degrees, random radius in
        // [radiusMin, radiusMax], converted to (x, y) around center.
        let angleDeg = Double.random(in: spec.angleRangeDeg)
        let angleRad = angleDeg * .pi / 180
        let r = Double.random(in: spec.radius)
        let x = spec.center.x + r * cos(angleRad)
        let y = spec.center.y + r * sin(angleRad)
        let dx = Double.random(in: spec.driftX)
        let dy = Double.random(in: spec.driftY)
        let lifetime = max(0.1, (spec.lifetime + Double.random(in: -spec.lifetimeJitter...spec.lifetimeJitter)) / 1000)
        let rot = Double.random(in: -spec.rotationJitterDeg...spec.rotationJitterDeg)
        let tplIdx = Int.random(in: 0..<imageMakers.count)
        let particle = ParticleAlive(
            templateIndex: tplIdx,
            spawnX: x, spawnY: y,
            driftX: dx, driftY: dy,
            scaleFrom: spec.scale.lowerBound,
            scaleTo: spec.scale.upperBound,
            rotationEndDeg: rot,
            lifetimeSec: lifetime,
            bornAt: Date()
        )
        particles.append(particle)
        // GC after lifetime expires so the array doesn't grow unbounded.
        DispatchQueue.main.asyncAfter(deadline: .now() + lifetime) {
            particles.removeAll { $0.id == particle.id }
        }
    }
}

#else
// macOS / non-UIKit fallback — never instantiated. Main view's overlay
// is wrapped in #if canImport(UIKit). Stub kept so other code that mentions
// the type compiles on macOS for Xcode preview iteration of non-particle code.
struct TokenCompanionParticleLayerView: View {
    var body: some View { EmptyView() }
}
#endif


// MARK: - Main animator view

// SwiftUI driver. Owns:
//   - displayedState / targetState pair for snappy any-to-any morphs
//   - morphProgress (0…1) driving each TokenCompanionMorphShape's animatableData
//   - idleAmplitude (1.0 normally, ramped to 0.1 during morphs and back)
// Idle math runs in TimelineView's body so it's frame-driven.

public struct TokenCompanionAnimator: View {
    @Binding private var externalState: TokenCompanionState
    @State private var internalState: TokenCompanionState = .idle
    private let usesExternalBinding: Bool

    // Visual state
    @State private var displayedState: TokenCompanionState = .idle
    @State private var targetState: TokenCompanionState = .idle
    @State private var morphProgress: Double = 1.0   // 0 = at displayedState, 1 = at targetState
    @State private var idleAmplitude: Double = 1.0
    @State private var animStart: Date = .distantPast
    // Gate for the particle emitter. Set false at the start of any transition
    // leaving a particle state — new spawns halt immediately, alive cells
    // continue their lifetime. Restored to true after morph completion
    // (when the new state's emitter is mounted, if applicable).
    @State private var particlesEmitting: Bool = true
    // Drives orphan layer opacity. Updated INSIDE withAnimation at
    // transition start so SwiftUI animates the per-state orphan opacities
    // (old state fades out, new state fades in) during the morph instead
    // of snapping when displayedState updates at morph completion.
    @State private var displayedOrphanState: TokenCompanionState = .idle

    public init() {
        self._externalState = .constant(.idle)
        self.usesExternalBinding = false
    }
    public init(state: Binding<TokenCompanionState>) {
        self._externalState = state
        self.usesExternalBinding = true
    }

    private var currentState: TokenCompanionState {
        usesExternalBinding ? externalState : internalState
    }

    public var body: some View {
        TimelineView(.animation) { context in
            let t = context.date.timeIntervalSince(animStart)
            // Whole-body idle: the JS engine writes each root part to
            // el.style.transform, so multiple root parts CLOBBER each other —
            // only the LAST one renders (e.g. waggle's sway overwrites its
            // breathe-y). Match that exactly by evaluating just the last root
            // part; combining them (the old behavior) added motion the web
            // preview never shows (e.g. an extra breathe scale during waggle).
            let rootTransform = idleParts(for: displayedState).last { $0.selector == nil }
                .map { evaluateIdle($0, t: t, amplitude: idleAmplitude) } ?? TokenCompanionIdleTransform()
            ZStack {
                // Z-order (back to front), matching the JS engine's SVG render order:
                //   1. Back-layer orphans (orphans tagged _layer: "back")
                //   2. Particle layer (per the source SVG's layer: "behind" hint)
                //   3. Shared morphable paths (body, head, hands, etc.)
                //   4. Front-layer orphans (default layer: "front", includes orphanSVG)
                //
                // .compositingGroup() flattens each state's orphan stack before the
                // opacity fade so overlapping transparent shapes don't double-blend
                // mid-fade (would otherwise look fragmented).
                ForEach(TokenCompanionState.allCases, id: \.self) { sn in
                    backOrphans(for: sn, t: t, amplitude: idleAmplitude)
                        .compositingGroup()
                        .opacity(sn == displayedOrphanState ? 1 : 0)
                }
                #if canImport(UIKit)
                if let spec = particleSpec(for: displayedState) {
                    TokenCompanionParticleLayerView(
                        spec: spec,
                        imageMakers: particleTemplates(for: displayedState).map { $0.imageMaker },
                        emitting: particlesEmitting,
                        canvasW: 76,
                        canvasH: 58
                    )
                    .allowsHitTesting(false)
                }
                #endif
                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "body", subpath: 0, in: displayedState),
                        to: segments(for: "body", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.6, lineCap: .butt, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("body", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "earL", subpath: 0, in: displayedState),
                        to: segments(for: "earL", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.4, lineCap: .butt, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("earL", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "earR", subpath: 0, in: displayedState),
                        to: segments(for: "earR", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.4, lineCap: .butt, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("earR", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "eyeL", subpath: 0, in: displayedState),
                        to: segments(for: "eyeL", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .fill(Color.white)
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("eyeL", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "eyeR", subpath: 0, in: displayedState),
                        to: segments(for: "eyeR", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .fill(Color.white)
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("eyeR", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "cheekL", subpath: 0, in: displayedState),
                        to: segments(for: "cheekL", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .fill(Color(.sRGB, red: 0.78824, green: 0.78824, blue: 0.78824, opacity: 1))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("cheekL", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "cheekR", subpath: 0, in: displayedState),
                        to: segments(for: "cheekR", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .fill(Color(.sRGB, red: 0.78824, green: 0.78824, blue: 0.78824, opacity: 1))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("cheekR", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "mouth", subpath: 0, in: displayedState),
                        to: segments(for: "mouth", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.3, lineCap: .round, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("mouth", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "footL", subpath: 0, in: displayedState),
                        to: segments(for: "footL", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.2, lineCap: .butt, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("footL", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "footR", subpath: 0, in: displayedState),
                        to: segments(for: "footR", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.2, lineCap: .butt, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("footR", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "armL", subpath: 0, in: displayedState),
                        to: segments(for: "armL", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.3, lineCap: .round, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("armL", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))

                Group {
                    TokenCompanionMorphShape(
                        from: segments(for: "armR", subpath: 0, in: displayedState),
                        to: segments(for: "armR", subpath: 0, in: targetState),
                        progress: morphProgress
                    )
                    .stroke(Color.white, style: StrokeStyle(lineWidth: 2.3, lineCap: .round, lineJoin: .miter))
                }
                .frame(width: 76, height: 58, alignment: .topLeading)
                .modifier(TokenCompanionElementIdleMod(e: idleForElement("armR", in: displayedState, t: t, amplitude: idleAmplitude, blinkSuppressed: displayedState != targetState)))


                ForEach(TokenCompanionState.allCases, id: \.self) { sn in
                    frontOrphans(for: sn, t: t, amplitude: idleAmplitude)
                        .compositingGroup()
                        .opacity(sn == displayedOrphanState ? 1 : 0)
                }
            }
            .frame(width: 76, height: 58)
            .scaleEffect(x: rootTransform.scale.width, y: rootTransform.scale.height, anchor: rootTransform.anchor)
            .rotationEffect(.degrees(rootTransform.rotationDegrees), anchor: rootTransform.anchor)
            .offset(rootTransform.translation)
        }
        .onAppear {
            animStart = Date()
            displayedState = currentState
            targetState = currentState
            displayedOrphanState = currentState
        }
        .onChange(of: currentState) { _, newValue in
            transition(to: newValue)
        }
    }

    private func transition(to newState: TokenCompanionState) {
        guard newState != targetState else { return }
        // Particle handoff: if we're leaving a state that emits particles
        // and heading somewhere with a different (or no) particle spec, stop
        // spawning immediately. Alive cells finish naturally during the morph.
        let fromHasParticles = particleSpec(for: displayedState) != nil
        // Two specs are "the same" if both are non-nil for now — a robust
        // equality check would require TokenCompanionParticleSpec: Equatable. For the
        // snowman this is sufficient because only one state has particles.
        let toHasParticles = particleSpec(for: newState) != nil
        if fromHasParticles && !toHasParticles {
            particlesEmitting = false
        }
        targetState = newState
        morphProgress = 0
        // Orphan crossfade: fade old state's orphans out + new state's orphans in,
        // both driven by displayedOrphanState changing INSIDE withAnimation.
        // Done over ~40% of morph duration to match the JS preview's pacing.
        withAnimation(.easeInOut(duration: 0.48)) {
            displayedOrphanState = newState
        }
        // Ramp idle amplitude down to 0.1
        withAnimation(.timingCurve(0.37, 0, 0.63, 1, duration: 0.48)) {
            idleAmplitude = 0.1
        }
        withAnimation(Animation.timingCurve(0.45, 0, 0.55, 1, duration: 1.2)) {
            morphProgress = 1.0
        }
        // After morph completes: snap displayedState forward, ramp idle back up,
        // and restore particle emission so the destination state's emitter (if any)
        // starts spawning.
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.2) {
            displayedState = targetState
            morphProgress = 1.0
            particlesEmitting = true
            withAnimation(.timingCurve(0.37, 0, 0.63, 1, duration: 0.48)) {
                idleAmplitude = 1.0
            }
        }
    }

    // Public helper for the no-binding init: programmatic state change.
    public mutating func setState(_ s: TokenCompanionState) {
        internalState = s
    }
}

// MARK: - Preview
#if DEBUG
struct TokenCompanionAnimator_Preview: PreviewProvider {
    static var previews: some View {
        StatePreviewWrapper()
    }
    struct StatePreviewWrapper: View {
        @State private var s: TokenCompanionState = .idle
        var body: some View {
            VStack {
                TokenCompanionAnimator(state: $s)
                Picker("State", selection: $s) {
                    ForEach(TokenCompanionState.allCases, id: \.self) { Text($0.rawValue).tag($0) }
                }.pickerStyle(.segmented)
            }.padding()
        }
    }
}
#endif
